apiVersion: v1
kind: Pod
metadata:
  name: $PODNAME
  labels:
    app: trex
spec:
  containers:
    - name:  trex
      image: $COMPONENT_CONTAINER_IMAGE
      ports:
        - containerPort: 8000
        