---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-and-test
spec:
  description: |
    An integration test which provisions an ephemeral namespace and deploys a container from a Konflux snapshot.
  params:
    - description: Snapshot of an application
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: Namespace where the the container will be deployed.
      name: NAMESPACE
      default: default
      type: string
    - description: Name of the pod and service to be tested (oc expose gives the service the same name as the pod)
      name: pod-and-svc-name
      default: rh-trex
      type: string
  tasks:
    - name: hello-world
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/sonam1412/rh-trex.git
          - name: revision
            value: main
          - name: pathInRepo
            value: .tekton/integration/tasks/sample-task.yaml