apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-container
spec:
  params:
    - name: serviceaccount-secret
      description: "Secret to service account that can access the ephemeral namespace"
    - name: SNAPSHOT
      description: The JSON string of the Snapshot under test
    - name: pod-name
      description: Name of the pod and service to be tested
  steps:
    - name: deploy-container
      image: registry.redhat.io/openshift4/ose-cli:latest
      imagePullPolicy: Always
      env:
        - name: COMPONENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['appstudio.openshift.io/component']
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: SECRETNAME
          value: $(params.serviceaccount-secret)
        - name: PODNAME
          value: $(params.pod-name)
      script: |
        #!/bin/bash
        set -ex
        set -o pipefail
       
        oc get secret $SECRETNAME --template '{{.data.kubeconfig}}' | base64 -d > /kubeconfig
        export KUBECONFIG=/kubeconfig

        dnf install -y jq gettext
        export COMPONENT_CONTAINER_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.components[] | select(.name == $component_name) | .containerImage' <<< "${SNAPSHOT}")

        echo "Echoing component container image"

        curl https://raw.githubusercontent.com/sonam1412/rh-trex/main/.tekton/integration/pod-and-svc.yaml | envsubst | oc apply -f - # create pod with test image
        CLUSTER_IP=$(oc expose pod $PODNAME -o jsonpath={.spec.clusterIP}) #expose pod port
        sleep 5 #make sure the pod is running
        oc run -i --tty --rm debug --image=curlimages/curl --restart=Never -- curl ${PODNAME}:8080
