apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-container
spec:
  params:
    - name: serviceaccount-secret
      description: "Secret to service account that can access the ephemeral namespace"
    - name: SNAPSHOT
      description: The JSON string of the Snapshot under test
    - name: svc-name
  steps:
    - name: echo
      image: registry.redhat.io/openshift4/ose-cli:4.13@sha256:73df37794ffff7de1101016c23dc623e4990810390ebdabcbbfa065214352c7c
      env:
        - name: COMPONENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['appstudio.openshift.io/component']
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: SECRETNAME
          value: $(params.serviceaccount-secret)
        - name: URL
          value: $(params.svc-name)
      script: |
        #!/bin/bash
        set -ex
        set -o pipefail
       
        oc get secret $SECRETNAME --template '{{.data.kubeconfig}}' | base64 -d > /kubeconfig
        export KUBECONFIG=/kubeconfig

        # Check the application endpoint
        ENDPOINT_OUTPUT=$(curl -k http://${HOST}:5432)
        echo -e "The endpoint outputs the following:\n ${ENDPOINT_OUTPUT}"
        echo -e "Snapshot output:\n ${SNAPSHOT}"

        echo "Hello World!"

        
