kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: rh-trex-integration-test
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: 'Namespace where the application is running'
      name: NAMESPACE
      default: "default"
      type: string
    - description: 'Expected output'
      name: EXPECTED_OUTPUT
      default: ""
      type: string
    - description: Name of the pod and service to be tested (oc expose gives the service the same name as the pod)
      name: pod-and-svc-name
      default: trex
      type: string
  tasks:
    - name: parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/integration-examples
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test_metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: provision-namespace
      runAfter:
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/provision-env-with-ephemeral-namespace/0.1/provision-env-with-ephemeral-namespace.yaml
      params:
        - name: KONFLUXNAMESPACE
          value: $(context.pipelineRun.namespace)
        - name: PIPELINERUN_NAME
          value: $(context.pipelineRun.name)
        - name: PIPELINERUN_UID
          value: $(context.pipelineRun.uid)
    - name: deploy-container
      runAfter:
        - provision-namespace
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/jencull/rh-trex.git
          - name: revision
            value: main
          - name: pathInRepo
            value: .tekton/integration/tasks/deploy.yaml
      params:
        - name: serviceaccount-secret
          value: $(tasks.provision-namespace.results.secretRef)
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: pod-name
          value: $(params.pod-and-svc-name)
    - name: integration-test
      runAfter:
        - deploy-container
      description: Set up DB, run integration tests, and read results
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: EXPECTED_OUTPUT
          value: $(params.EXPECTED_OUTPUT)
      taskSpec:
        params:
        - name: SNAPSHOT
        - name: NAMESPACE
        - name: EXPECTED_OUTPUT
        results:
        - name: TEST_OUTPUT
          description: Test output
        steps:
        - image: registry.redhat.io/openshift4/ose-cli:latest
          env:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
          - name: NAMESPACE
            value: $(params.NAMESPACE)
          - name: EXPECTED_OUTPUT
            value: $(params.EXPECTED_OUTPUT)
          script: |
            # Install Deps
            dnf -y install jq git make golang podman

            # Runtime Env Config
            export GOPATH=$HOME/.go
            export PATH="$PATH:$GOPATH/bin"
            go install gotest.tools/gotestsum@latest  

            # Set Vars
            TARGET_COMPONENT_NAME="rh-trex"
            REPO_URL=$(echo $SNAPSHOT | jq -r '.components[] | select(.name == "rh-trex").source.git.url')
            REPO_COMMIT=$(echo $SNAPSHOT | jq -r '.components[] | select(.name == "rh-trex").source.git.revision')
            test_output_file=${PWD}/test_output.json

            # Log Vars for Tracibility
            echo "REPO_URL: $REPO_URL"
            echo "TARGET_COMPONENT_NAME: $TARGET_COMPONENT_NAME"
            echo "REPO_COMMIT: $REPO_COMMIT"
            echo "SNAPSHOT: $(echo $SNAPSHOT | jq)"

            # Clone Repo and checkout at snapshot commit
            git clone $REPO_URL $TARGET_COMPONENT_NAME
            cd $TARGET_COMPONENT_NAME
            git checkout $REPO_COMMIT

            # Wait for the DB sidecar to be ready
            echo "[INFO] Waiting for database to be ready for connection"
              timeout 5m bash -c 'until echo > /dev/tcp/localhost/5432; do sleep 2s; done'

            # Run integration tests with JSON output
            make ci-test-integration integration_test_json_output="$test_output_file"

            # Read, process, and write output in accepted format
            # Formatting docs: https://redhat-appstudio.github.io/book/ADR/0030-tekton-results-naming-convention.html#test_output-schema-validation
            FAILURES=$(cat $test_output_file | jq 'select(.Action == "fail")' | jq -r --slurp 'length')
            SUCCESSES=$(cat $test_output_file | jq 'select(.Action == "pass")' | jq -r --slurp 'length')
            # Hard-code warnings
            WARNINGS=0
            RESULT="$(if [[ $FAILURES == 0 ]]; then echo "SUCCESS"; else echo "FAILURE"; fi)"
            # TODO: Switch to rfc-3339 when RHTAP changes the schema
            # TIMESTAMP="$(date --rfc-3339=seconds)"
            TIMESTAMP="$(date +%s)"
            TEST_OUTPUT=$(jq -r --null-input \
              --arg failures $FAILURES \
              --arg successes $SUCCESSES \
              --arg warnings $WARNINGS \
              --arg result "$RESULT" \
              --arg timestamp "$TIMESTAMP" \
              '{"result": $result, "successes": $successes|tonumber, "failures": $failures|tonumber, "warnings": $warnings|tonumber, "timestamp": $timestamp}' \
            )
            echo -n "$TEST_OUTPUT" | tee $(results.TEST_OUTPUT.path)
        sidecars:
          - image: docker.io/library/postgres:14.15
            name: database-test
            env:
            - name: PGDATA
              value: /work/data
            - name: POSTGRES_DB
              value: rhtrex
            - name: POSTGRES_PASSWORD
              value: foobar-bizz-buzz
            - name: POSTGRES_USER
              value: trex
            volumeMounts:
              - mountPath: /work
                name: data
        volumes:
          - name: data
            emptyDir: {}